"""added userinfo table in post db

Revision ID: a65deb81fa14
Revises: 011b0b60eaac
Create Date: 2023-07-16 13:54:32.878836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65deb81fa14'
down_revision = '011b0b60eaac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userInformationPost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userInformationPost_first_name'), 'userInformationPost', ['first_name'], unique=False)
    op.create_index(op.f('ix_userInformationPost_id'), 'userInformationPost', ['id'], unique=False)
    op.create_index(op.f('ix_userInformationPost_last_name'), 'userInformationPost', ['last_name'], unique=False)
    op.create_index(op.f('ix_userInformationPost_owner_id'), 'userInformationPost', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userInformationPost_owner_id'), table_name='userInformationPost')
    op.drop_index(op.f('ix_userInformationPost_last_name'), table_name='userInformationPost')
    op.drop_index(op.f('ix_userInformationPost_id'), table_name='userInformationPost')
    op.drop_index(op.f('ix_userInformationPost_first_name'), table_name='userInformationPost')
    op.drop_table('userInformationPost')
    # ### end Alembic commands ###
